owner: gzombiejun
repo: upptime

sites:
  - name: Undertale社区维基 - UTCWIKI
    url: https://utcwiki.com
  - name: Undertale社区维基 测试站 - UTCWIKIT
    url: https://test.utcwiki.com
  - name: Undertale自由维基 - UTFWIKI
    url: https://free.utcwiki.com
  - name: Undertale社区档案馆（API-获取item） - UTCARC
    url: https://apiarc.utcwiki.com/item/show?limit=1
  - name: Undertale社区项目路线图 - UTCPRP
    url: https://road.utcwiki.com

status-website:
  theme: light
  cname: status.utcwiki.com
  logoUrl: https://utcwiki.com/resources/assets/wiki.png
  name: UTCP在线状态监测

i18n:
  activeIncidents: 提示
  allSystemsOperational: 一切正常
  incidentReport: "查看事件#$NUMBER →"
  activeIncidentSummary: 于 $DATE 开始，共有 $POSTS 条帖子
  incidentTitle: Incident $NUMBER Details
  incidentDetails: Incident Details
  incidentFixed: Fixed
  incidentOngoing: 处理中
  incidentOpenedAt: 开始于
  incidentClosedAt: 结束于
  incidentViewOnGitHub: View and Subscribe on GitHub
  incidentCommentSummary: Posted at $DATE by $AUTHOR
  incidentBack: ← 返回
  pastIncidents: Past Incidents
  pastIncidentsResolved: Resolved in $MINUTES minutes with $POSTS
  liveStatus: 在线状态
  overallUptime: "在线时间比例：$UPTIME"
  overallUptimeTitle: 在线时间比例
  averageResponseTime: "平均响应时间：$TIMEms"
  averageResponseTimeTitle: 平均响应时间
  sevenDayResponseTime: 一周内的平均响应时间
  responseTimeMs: 响应时间（毫秒）
  up: 正常
  down: 宕机
  degraded: Degraded
  ms: 毫秒
  loading: 加载中
  navGitHub: GitHub
  footer: 这个页面由[Upptime](https://upptime.js.org)构建。
  rateLimitExceededTitle: Rate limit exceeded
  rateLimitExceededIntro: You have exceeded the number of requests you can do in an hour, so you'll have to wait before accessing this website again. Alternately, you can add a GitHub Personal Access Token to continue to use this website.
  rateLimitExceededWhatDoesErrorMean: What does this error mean?
  rateLimitExceededErrorMeaning: This website uses the GitHub API to access real-time data about our websites' status. By default, GitHub allows each IP address 60 requests per hour, which you have consumed.
  rateLimitExceededErrorHowCanFix: How can I fix it?
  rateLimitExceededErrorFix: You can wait for another hour and your IP address' limit will be restored. Alternately, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
  rateLimitExceededGeneratePAT: Learn how to generate a Personal Access Token
  rateLimitExceededHasSet: You have a personal access token set.
  rateLimitExceededRemoveToken: Remove token
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Copy and paste your token
  rateLimitExceededSaveToken: Save token
  errorTitle: An error occurred
  errorIntro: An error occurred in trying to get the latest status details.
  errorText: You can try again in a few moments.
  errorHome: Go to the homepage
  pastScheduledMaintenance: Past Scheduled Maintenance
  scheduledMaintenance: Scheduled Maintenance
  scheduledMaintenanceSummaryStarted: Started at $DATE for $DURATION minutes
  scheduledMaintenanceSummaryStarts: Starts at $DATE for $DURATION minutes
  startedAt: 已开始于
  startsAt: 将开始于
  duration: 期间
  durationMin: $DURATION 分钟
  incidentCompleted: Completed
  incidentScheduled: Scheduled
  duration24H: 一天内
  duration7D: 一周内
  duration30D: 一月内
  duration1Y: 一年内
  durationAll: 所有时间
